<a href="https://colab.research.google.com/github/kalumay/Major/blob/master/RehateNtoxic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data_path='/content/drive/MyDrive/Colab Notebooks/Datas/'

In [ ]:
import pandas as pd
ds=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datas/labeled_data.csv/labeled_data.csv')

In [ ]:
print(ds.to_string)

<bound method DataFrame.to_string of        Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                      

In [ ]:
for column in ds.columns:
    print(f"\nColumn: {column}")
    print(ds[column].value_counts())



Column: Unnamed: 0
0        1
16934    1
16907    1
16906    1
16905    1
        ..
8487     1
8486     1
8485     1
8484     1
25296    1
Name: Unnamed: 0, Length: 24783, dtype: int64

Column: count
3    22807
6     1571
4      211
9      167
7       27
Name: count, dtype: int64

Column: hate_speech
0    19790
1     3419
2     1251
3      287
4       21
5        7
6        5
7        3
Name: hate_speech, dtype: int64

Column: offensive_language
3    13383
2     4246
0     3475
1     2066
6      857
5      369
4      251
9       66
8       37
7       33
Name: offensive_language, dtype: int64

Column: neither
0    18892
3     2790
1     1694
2     1200
6      103
5       54
4       35
9        5
8        5
7        5
Name: neither, dtype: int64

Column: class
1    19190
2     4163
0     1430
Name: class, dtype: int64

Column: tweet
!!! RT @mayasolovely: As a woman you shouldn't complain about cleaning up your house. &amp; as a man you should always take the trash out...          1
RT 

In [ ]:
columns_to_clean = ['tweet']  # Replace with actual column names

# Remove words starting with "@" in the specified columns
for column in columns_to_clean:
    ds[column] = ds[column].str.replace(r'\S*@\S*', '', regex=True)

print(ds)



       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT  A

In [ ]:
row_65 = ds.iloc[66]
print(row_65)

Unnamed: 0                                                          66
count                                                                3
hate_speech                                                          0
offensive_language                                                   1
neither                                                              2
class                                                                2
tweet                  http://t.co/3gzUpfuMev" woof woof and hot soles
Name: 66, dtype: object


In [ ]:
columns_to_clean = ['tweet']  # Replace with actual column names

# Clean special characters in the specified columns
for column in columns_to_clean:
    ds[column] = ds[column].str.replace('[^a-zA-Z0-9\s]', '', regex=True)

# Display the cleaned DataFrame
print(ds)


       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0       RT  As a

In [ ]:
row_55 = ds.iloc[56]
print(row_55)

Unnamed: 0                                                           56
count                                                                 3
hate_speech                                                           0
offensive_language                                                    3
neither                                                               0
class                                                                 1
tweet                  And ima steal his cat n replace it with a pit...
Name: 56, dtype: object


In [ ]:
# Remove rows with null values in the specified columns
ds.dropna(subset=columns_to_clean, inplace=True)

# Display the DataFrame after removing null values
print(ds)

       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0       RT  As a

In [ ]:
import nltk
from nltk.corpus import stopwords

# Download NLTK stopwords data
nltk.download('stopwords')

columns_to_clean = ['tweet']  # Replace with actual column names

# Remove stopwords in the specified columns
stop_words = set(stopwords.words('english'))
for column in columns_to_clean:
    ds[column] = ds[column].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stop_words]))

# Display the DataFrame after removing stopwords
print(ds)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      RT woman 

In [ ]:
columns_to_clean = ['tweet']  # Replace with actual column names

# Remove "RT" in the specified columns
for column in columns_to_clean:
    ds[column] = ds[column].str.replace(r'\bRT\b', '', regex=True)

print(ds)


       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0       woman sh

In [17]:
import nltk
from nltk.tokenize import word_tokenize

# Download NLTK tokenization data
nltk.download('punkt')

# Assuming your dataset is loaded into a DataFrame called 'ds'
# Replace 'ds' with the actual name of your DataFrame
# Replace 'tweet' with the actual name of your text column

# Specify the column(s) you want to tokenize
columns_to_tokenize = ['tweet']  # Replace with actual column names

# Convert the column to string type
ds['tweet'] = ds['tweet'].astype(str)

# Tokenize text in the specified columns
for column in columns_to_tokenize:
    ds['tweet'] = ds['tweet'].apply(lambda x: word_tokenize(x))

# Display the DataFrame after tokenization
print(ds)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


       Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      [[, 'woma

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Convert the tokenized text back to string
ds['tweet'] = ds['tweet'].apply(lambda x: ' '.join(x))

# Create a TF-IDF Vectorizer instance
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 1))  # Adjust parameters as needed

# Fit and transform the text data
X_tfidf = vectorizer.fit_transform(ds['tweet'])

# Display the feature names
feature_names = vectorizer.get_feature_names_out()
print("Feature names:", feature_names)

# Display the TF-IDF matrix
print("TF-IDF matrix:")
print(X_tfidf.toarray())


Feature names: ['10' '100' '1000' ... 'zip' 'zone' 'zoo']
TF-IDF matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
# Assuming 'ds' is your DataFrame and 'target' is the column with labels
y = ds['class']

# Display class distribution
class_distribution = y.value_counts()
print("Class Distribution:")
print(class_distribution)


Class Distribution:
1    19190
2     4163
0     1430
Name: class, dtype: int64


In [25]:
print(y.value_counts())


offensive_language  hate_speech  neither
3                   0            0          13306
2                   1            0           2815
0                   0            3           2753
2                   0            1           1384
1                   2            0           1009
                                            ...  
                    7            1              1
2                   2            5              1
0                   5            4              1
                    4            2              1
                    6            3              1
Length: 75, dtype: int64


In [26]:
from sklearn.model_selection import train_test_split

# Set a threshold for considering classes as rare
threshold = 2

# Identify combinations with counts less than the threshold
rare_classes = ds[ds.groupby(['offensive_language', 'hate_speech', 'neither']).transform('size') < threshold].index

# Replace rare classes with a new class 'rare_class'
ds.loc[rare_classes] = 'rare_class'

# Define feature matrix 'X' and target variable 'y'
X = ds[['tweet', 'count']]  # Features
y = ds[['offensive_language', 'hate_speech', 'neither']]  # Targets

# Split the data into training and testing sets with stratification
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Display the modified target variable 'y'
print("Modified Target Variable 'y':")
print(y)


Modified Target Variable 'y':
      offensive_language hate_speech neither
0                      0           0       3
1                      3           0       0
2                      3           0       0
3                      2           0       1
4                      6           0       0
...                  ...         ...     ...
24778                  2           0       1
24779                  1           0       2
24780                  3           0       0
24781                  6           0       0
24782                  0           0       3

[24783 rows x 3 columns]


In [27]:
# Display feature matrix 'X'
print("Feature Matrix 'X':")
print(X)



Feature Matrix 'X':
                                                   tweet count
0      [ 'woman ' , 'shouldnt ' , 'complain ' , 'clea...     3
1      [ 'boy ' , 'dats ' , 'coldtyga ' , 'dwn ' , 'b...     3
2      [ 'Dawg ' , 'ever ' , 'fuck ' , 'bitch ' , 'st...     3
3                      [ 'look ' , 'like ' , 'tranny ' ]     3
4      [ 'shit ' , 'hear ' , 'might ' , 'true ' , 'mi...     6
...                                                  ...   ...
24778  [ 'yous ' , 'muthafin ' , 'lie ' , 'right ' , ...     3
24779  [ 'youve ' , 'gone ' , 'broke ' , 'wrong ' , '...     3
24780  [ 'young ' , 'buck ' , 'wan ' , 'na ' , 'eat '...     3
24781  [ 'youu ' , 'got ' , 'wild ' , 'bitches ' , 't...     6
24782  [ 'Ruffled ' , 'Ntac ' , 'Eileen ' , 'Dahlia '...     3

[24783 rows x 2 columns]


In [28]:
print(f"num test tweet: {y_test.shape[0]}")
print(f"num train tweet: {y_train.shape[0]}")

num test tweet: 4957
num train tweet: 19826


In [29]:
import numpy as np

# Define the true labels (ground truth) from dataset
y_true = ds[['offensive_language', 'hate_speech', 'neither']]

random_predictions = np.random.randint(2, size=(len(ds), 3))

# Convert the array of predictions to a DataFrame with appropriate column names
y_pred = pd.DataFrame(random_predictions, columns=['offensive_language', 'hate_speech', 'neither'])

In [31]:
print("Data Types in y_true:")
print(y_true.dtypes)

print("\nData Types in y_pred:")
print(y_pred.dtypes)


Data Types in y_true:
offensive_language    object
hate_speech           object
neither               object
dtype: object

Data Types in y_pred:
offensive_language    int64
hate_speech           int64
neither               int64
dtype: object


In [33]:
# Replace non-numeric values with 0
y_true = y_true.apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)
y_pred = y_pred.astype(int)

In [35]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Flatten multi-class targets into a single column
label_encoder = LabelEncoder()
y_true_flat = label_encoder.fit_transform(y_true.values.argmax(axis=1))
y_pred_flat = label_encoder.transform(y_pred.values.argmax(axis=1))

# Compute evaluation metrics
accuracy = accuracy_score(y_true_flat, y_pred_flat)
precision = precision_score(y_true_flat, y_pred_flat, average='weighted')
recall = recall_score(y_true_flat, y_pred_flat, average='weighted')
f1 = f1_score(y_true_flat, y_pred_flat, average='weighted')
conf_matrix = confusion_matrix(y_true_flat, y_pred_flat)

# Display the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.5159
Precision: 0.6295
Recall: 0.5159
F1 Score: 0.5625
Confusion Matrix:
[[11927  4892  2383]
 [  922   336   165]
 [ 2608  1028   522]]
